# Generated by Django 4.2.7 on 2023-11-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=260, null=True)),
                ('address', models.CharField(max_length=256, unique=True)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
