# Generated by Django 4.2.7 on 2023-11-29 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_concertcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=260, null=True)),
                ('starts_at', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tickets_left', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='concertcategory',
            options={'ordering': ['-name'], 'verbose_name': 'concert_category', 'verbose_name_plural': 'concert categories'},
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_full_name', models.CharField(max_length=120)),
                ('payment_method', models.CharField(choices=[('ETH', 'Ethereum'), ('BTC', 'Bitcoin'), ('USDT', 'Tether'), ('SOL', 'Solana')], default='ETH', max_length=4)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BinaryField(default=True)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.concert')),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='categories',
            field=models.ManyToManyField(to='tickets.concertcategory'),
        ),
        migrations.AddField(
            model_name='concert',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.venue'),
        ),
    ]
